# Generated by Django 3.2.20 on 2023-09-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type_api_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_type_api_service",
                        to="zgw_consumers.service",
                    ),
                ),
                (
                    "objects_api_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects_api_service",
                        to="zgw_consumers.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objects API client configuration",
            },
        ),
    ]
