# Generated by Django 5.2.9 on 2025-12-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objectsapiclient", "0003_rename_config_model_fields"),
        ("zgw_consumers", "0016_auto_20220818_1412"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objectsclientconfiguration",
            options={"verbose_name": "Objects API client configuration"},
        ),
        migrations.AlterField(
            model_name="objectsclientconfiguration",
            name="object_type_api_service_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_type_api_service_config",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="objectsclientconfiguration",
            name="objects_api_service_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects_api_service_config",
                to="zgw_consumers.service",
            ),
        ),
    ]
